parameters:
#    aiconoa_user.example.class: Aiconoa\UserBundle\Example

services:
#    aiconoa_user.example:
#        class: %aiconoa_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
