aiconoa_user:
    resource: "@AiconoaUserBundle/Resources/config/routing.yml"
    prefix:   /

aiconoa_joke:
    resource: "@AiconoaJokeBundle/Resources/config/routing.yml"
    prefix:   /

aiconoa_app:
    resource: "@AiconoaAppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: AiconoaAppBundle:Secured:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
