services:
    aiconoa_joke.jokeservice:
        #class: Aiconoa\JokeBundle\Service\MockJokeService
        class: Aiconoa\JokeBundle\Service\DoctrineJokeService
        arguments: [@doctrine]

    aiconoa_joke.security.access.post_voter:
        class:      Aiconoa\JokeBundle\Voter\JokeVoter
        public:     false
        tags:
           - { name: security.voter }

    aiconoa_joke.twig.extension.joke_action:
      class: Aiconoa\JokeBundle\Extensions\Twig\JokeActionHelper
      arguments:
        router: "@router"
        securityContext: "@security.context"
      tags:
       - { name: twig.extension }