aiconoa_app_pages:
    resource: "Aiconoa\AppBundle\Controller\DefaultController"
    type:     annotation

aiconoa_login:
    resource: "Aiconoa\AppBundle\Controller\SecuredController"
    type:     annotation